### ISSUE TITLE
Webpage to send title boot mail

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/Mail-Go#13]
When we made the homebrew mail patcher, we enabled an option in the nwc24msg.cfg to do titlebooting. That can be used to fix bricks - it can wake up the Wii and boot to the Homebrew Channel (if someone isn't using Priiloader, BootMii, or the recovery mode for some reason).

I'm thinking we can put in a webpage to enter your Wii Number and it'll send the titleboot mail. However, since the Wii rejects mail from unregistered addresses, we'd probably have to make the mail be from w9999999999990000 (Nintendo's special address used to send out announcements) and assume that will work.

**Comment by KcrPL** [comment]
Nice. Didn't know that Wii Mail could do that.

**Comment by InternalLoss** [comment]
Update on this, it seems that title-booting only works from Announcement files? (Which would make more sense since title booting would be more useful for like an announcement). But, since we do set it to non-zero, it should work; this means that in theory we could help someone if their Wii decides to be an idiot.

**Comment by InternalLoss** [comment]
Closing; Boot mail can only be sent from a WC24 file DL task (not mail).
