### ISSUE TITLE
Make purge script

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/Mail-Go#23]
I need a mail purge script that deletes old mail, like with this command:

```DELETE FROM WC24Mail.mails WHERE `timestamp` < NOW() - INTERVAL 28 DAY;```

It also needs to be callable by a Crontab, I'm not sure how that'd work in Go (it'd be nice to have the purge script be in Go to be consistent).

[This old PHP script works](https://github.com/RiiConnect24/Mail/blob/master/clean/PurgeOld.php), but since we don't use PHP anymore we shouldn't use it. There's also a script to make all sent mail be marked as unsent, but I'm not sure why.

I don't understand why the PHP purge script purges mail that hasn't been sent only, I know we have a delete script that the Wii calls but if it didn't get to them, they should be deleted as well?

@pokeacer can you explain both things I mentioned above? I think you were the one who made it?

Also, I made this into a Python script but I just removed it because it didn't work (I manually purged the mail just now with MySQL console).

**Comment by caution3** [comment]
We plan to fix this issue in Mail-GO v1.3 and (assuming the script is working) is ready to go if I remember correctly. I'll double check later after school.

**Comment by InternalLoss** [comment]
Turns out I never actually replied to this? not even @ghost... okay

Anyways, that MySQL code deletes any mail in the database that is over 28 days old; with Wiis currently checking 144 times a day (6 times an hour * 24 hours), there is very little reason why 28 day+ old mail should be kept in the database. There is also another command after it that optimises the table iirc?

**Comment by larsenv** [comment]
I forgot this issue was open. We have a MySQL task set up to purge mails that have been sent that runs every day or so. It's not part of the code nor needs to be...
