### ISSUE TITLE
Use snowflakes

### ISSUE THREAD

**Issue by spotlightishere** [RiiConnect24/Mail-Go#8]
It's been discussed to use snowflakes.
Observe the following:
![Screenshot of database](https://spotlight-thinks-awoo.should-be.legal/6ea8d6.png)

If we used a snowflake, we could strike `mail_id` and `timestamp` out with one `INT(18)`.

**Comment by spotlightishere** [comment]
https://github.com/bwmarrin/snowflake seems like an extremely good candidate.

**Comment by spotlightishere** [comment]
This would still be nice to have. We potentially could eradicate meaningful message IDs. A migration plan should be made.

**Comment by 6100m** [comment]
I had a similar idea Spotlight, as a matter of fact. I will try to get this done before we release this for WiiLink24, but my idea was this:
Let's use the Wii Number as a example.
AAAAAAAA = 0000-0000-0000-0000
What's happening with that Spotlight, is basically this. If we do 100x100, we get 10000 possible Wii number combinations of that four-digit section, which is actually one more than we need.
That comes useful, which I will explain later on.
So basically each of those two characters can represent four numbers. If it's AA, it's 0000, if it's AB, it's 0001.
Since a Wii Number has 16 numbers, we need four 2 character nodes.
So now, to put that into simple terms. 😄 
ABACADAE 0001-0002-0003-0004
I know that's not a valid Wii number, but yeah, that's kinda the idea I had.
To explain all possible characters it uses, it uses about 100.
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%^&*(){}[]\|:;"'<,>.?/_-+=`~0123456789§ßµ±àå

This could be theoretically also applied to the character ID, although I am not sure.

**Comment by Artuto** [comment]
![image](https://user-images.githubusercontent.com/9273973/97818771-09b68600-1c6a-11eb-86f7-e0969a315fe2.png)

**Comment by Artuto** [comment]
Thats not even what it was suggested for

**Comment by KcrPL** [comment]
What kind of sorcery is this?

**Comment by larsenv** [comment]
What a great way to revive an issue that was made 2 years ago. 🙄

**Comment by larsenv** [comment]
By the way, snowflakes suck. Although we don't use it, each piece of mail has 2 UUIDs to associate the mail with, so we don't really need snowflakes.

**Comment by spotlightishere** [comment]
Primarily, snowflakes (if used) would coincide best with #6, in which the mail system formulates mail to be delivered, stripping most user-provided content that could be abused (i.e. various headers). Obviously this was never implemented, but it may be worth keeping it open in case such ever happens.
